version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: 'awp'
      POSTGRES_PASSWORD: 'awp'
    ports:
      - "5432:5432"
  server:
    build:
      context: server
    ports:
      - "8080:8080"
    depends_on:
      - db